/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BtcTxVerifier } from "./BtcTxVerifier";
export * as factories from "./factories";
export { BtcTxVerifier__factory } from "./factories/BtcTxVerifier__factory";
